#!/bin/bash
PROGNAME=`basename $0`
DATE=`date`
if [ "$PROGNAME" == "machine-reserve" ]; then
  username=$USER
  if [ "x${1}" != "x" ]; then
    username=$1
  fi
  sed -e "s/STATUS/Reserved by $username/g" -e "s/DATE/$DATE/g" /usr/local/etc/motd.template > /etc/motd
  echo "$DATE:Reserved by $username" >> /var/log/machine-status.log
elif [ "$PROGNAME" == "machine-release" ]; then
  sed -e "s/STATUS/Available/g" -e "s/DATE/$DATE/g" /usr/local/etc/motd.template > /etc/motd
  echo "$DATE:Released" >> /var/log/machine-status.log
elif [ "$PROGNAME" == "machine-report" ]; then
  cat /var/log/machine-status.log
  exit
fi
echo
cat /etc/motd
